import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReduxProviders } from '@/redux/Provider'
import { Provider } from '@/components/session-provider'
import { Toaster } from '@/components/ui/sonner'
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className='dark'>
      <ReduxProviders>
        <Provider>
          <body className={inter.className}>
            <NextTopLoader template='<div class="bar" role="bar"><div class="peg"></div></div>' />
            {children}
          </body>
          <Toaster />

        </Provider>
      </ReduxProviders>
    </html>
  )
}
